### ISSUE TITLE
TODO in sapper_rework.sp

### ISSUE THREAD

**Issue by Nopied** [TeamPotry/plugins_in_FF2#1]
- [x] 새퍼에 당한 상태의 데미지 보정
- [x] CustomCTFSapper 완성
- [x] 데드링어, 은폐 상태일 경우, 새퍼 사용 불가
- [x] 새퍼의 유효 사거리에 있는 적의 머리에 튜토리얼 텍스트 표시
- [x] 아군이 새퍼에 당하고 있는 경우, 새퍼에 데미지를 입힐 수 있는 옵션에 한하여 기절 시간 안에 제거

- [x] 절차주의 새퍼: 붙이면 적의 HP, 위치 장소를 최대 4초 전으로 되돌려 놓습니다.
> 4초 동안 왔던 위치를 되돌아 감.

**Comment by Nopied** [comment]
#2 로 인해 잠시 지연되고 있습니다.
